
package handleClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HandlerWSImplService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/DWPmv30SoapHandlers/handle?wsdl")
public class HandlerWSImplService
    extends Service
{

    private final static URL HANDLERWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HANDLERWSIMPLSERVICE_EXCEPTION;
    private final static QName HANDLERWSIMPLSERVICE_QNAME = new QName("http://soap/", "HandlerWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DWPmv30SoapHandlers/handle?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HANDLERWSIMPLSERVICE_WSDL_LOCATION = url;
        HANDLERWSIMPLSERVICE_EXCEPTION = e;
    }

    public HandlerWSImplService() {
        super(__getWsdlLocation(), HANDLERWSIMPLSERVICE_QNAME);
    }

    public HandlerWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HANDLERWSIMPLSERVICE_QNAME, features);
    }

    public HandlerWSImplService(URL wsdlLocation) {
        super(wsdlLocation, HANDLERWSIMPLSERVICE_QNAME);
    }

    public HandlerWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HANDLERWSIMPLSERVICE_QNAME, features);
    }

    public HandlerWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HandlerWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HandlerWS
     */
    @WebEndpoint(name = "HandlerWSImplPort")
    public HandlerWS getHandlerWSImplPort() {
        return super.getPort(new QName("http://soap/", "HandlerWSImplPort"), HandlerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HandlerWS
     */
    @WebEndpoint(name = "HandlerWSImplPort")
    public HandlerWS getHandlerWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "HandlerWSImplPort"), HandlerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HANDLERWSIMPLSERVICE_EXCEPTION!= null) {
            throw HANDLERWSIMPLSERVICE_EXCEPTION;
        }
        return HANDLERWSIMPLSERVICE_WSDL_LOCATION;
    }

}
