
package handleClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HandlerWS", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HandlerWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "personToString", targetNamespace = "http://soap/", className = "handleClient.PersonToString")
    @ResponseWrapper(localName = "personToStringResponse", targetNamespace = "http://soap/", className = "handleClient.PersonToStringResponse")
    @Action(input = "http://soap/HandlerWS/personToStringRequest", output = "http://soap/HandlerWS/personToStringResponse")
    public String personToString(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOldestFamily", targetNamespace = "http://soap/", className = "handleClient.GetOldestFamily")
    @ResponseWrapper(localName = "getOldestFamilyResponse", targetNamespace = "http://soap/", className = "handleClient.GetOldestFamilyResponse")
    @Action(input = "http://soap/HandlerWS/getOldestFamilyRequest", output = "http://soap/HandlerWS/getOldestFamilyResponse")
    public String getOldestFamily(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Family> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://soap/", className = "handleClient.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://soap/", className = "handleClient.SayHiResponse")
    @Action(input = "http://soap/HandlerWS/sayHiRequest", output = "http://soap/HandlerWS/sayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addChildAges", targetNamespace = "http://soap/", className = "handleClient.AddChildAges")
    @ResponseWrapper(localName = "addChildAgesResponse", targetNamespace = "http://soap/", className = "handleClient.AddChildAgesResponse")
    @Action(input = "http://soap/HandlerWS/addChildAgesRequest", output = "http://soap/HandlerWS/addChildAgesResponse")
    public int addChildAges(
        @WebParam(name = "arg0", targetNamespace = "")
        Family arg0);

    /**
     * 
     * @return
     *     returns java.util.List<handleClient.Family>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createFamilies", targetNamespace = "http://soap/", className = "handleClient.CreateFamilies")
    @ResponseWrapper(localName = "createFamiliesResponse", targetNamespace = "http://soap/", className = "handleClient.CreateFamiliesResponse")
    @Action(input = "http://soap/HandlerWS/createFamiliesRequest", output = "http://soap/HandlerWS/createFamiliesResponse")
    public List<Family> createFamilies();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addIntList", targetNamespace = "http://soap/", className = "handleClient.AddIntList")
    @ResponseWrapper(localName = "addIntListResponse", targetNamespace = "http://soap/", className = "handleClient.AddIntListResponse")
    @Action(input = "http://soap/HandlerWS/addIntListRequest", output = "http://soap/HandlerWS/addIntListResponse")
    public String addIntList(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonAge", targetNamespace = "http://soap/", className = "handleClient.GetPersonAge")
    @ResponseWrapper(localName = "getPersonAgeResponse", targetNamespace = "http://soap/", className = "handleClient.GetPersonAgeResponse")
    @Action(input = "http://soap/HandlerWS/getPersonAgeRequest", output = "http://soap/HandlerWS/getPersonAgeResponse")
    public int getPersonAge(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

}
